azure:
  free_disk_space: true
build_platform:
  linux_aarch64: linux_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_forge_output_validation: true
